### ISSUE TITLE
Exception in thread "main" com.starbase.starteam.NoSuchPropertyException

### ISSUE THREAD

**Issue by planestraveler** [planestraveler/git-starteam#44]
Note to myself:

While running in the conversion on a random project, I've encountered this stack trace
Exception in thread "main" com.starbase.starteam.NoSuchPropertyException:
  at com.starbase.starteam.Type.propertyForName(Type.java:365)
  at com.starbase.starteam.Type.propertiesForNames(Type.java:452)
  at com.starbase.starteam.ItemList.populateNow(ItemList.java:210)
  at org.sync.GitImporter.recoverDeleteInformation(GitImporter.java:502)
  at org.sync.GitImporter.generateFastImportStream(GitImporter.java:233)
  at org.sync.GitImporter.generateByLabelImport(GitImporter.java:685)
  at org.sync.MainEntry.main(MainEntry.java:195)

**Comment by planestraveler** [comment]
Experiment have shown that the commit information isn't lost, only degraded.
