### ISSUE TITLE
Null pointer exception after the first git fast-import

### ISSUE THREAD

**Issue by arpadhajdu** [planestraveler/git-starteam#61]
Hello,

I am experimenting with Starteam export using git-starteam.
I managed to compile the jar file and connect to the Starteam server.

When I am trying to export any project I am receiving a java.lang.nullpointerexception:

2016-12-16 16:17:21 Importing view Project onto null (1/26)
2016-12-16 16:17:21 View configuration label <Project 1.0 - Initial> (1/21)
2016-12-16 16:17:22 fast-import:git-fast-import statistics:
2016-12-16 16:17:22 fast-import:---------------------------------------------------------------------
2016-12-16 16:17:22 fast-import:Alloc'd objects:       5000
2016-12-16 16:17:22 fast-import:Total objects:          133 (         1 duplicates                  )
2016-12-16 16:17:22 fast-import:      blobs  :           70 (         1 duplicates         59 deltas of         64 attempts)
2016-12-16 16:17:22 fast-import:      trees  :           42 (         0 duplicates         28 deltas of         40 attempts)
2016-12-16 16:17:22 fast-import:      commits:           21 (         0 duplicates          0 deltas of          0 attempts)
2016-12-16 16:17:22 fast-import:      tags   :            0 (         0 duplicates          0 deltas of          0 attempts)
2016-12-16 16:17:22 fast-import:Total branches:           1 (         1 loads     )
2016-12-16 16:17:22 fast-import:      marks:           1024 (        92 unique    )
2016-12-16 16:17:22 fast-import:      atoms:             72
2016-12-16 16:17:22 fast-import:Memory total:          2344 KiB
2016-12-16 16:17:22 fast-import:       pools:          2110 KiB
2016-12-16 16:17:22 fast-import:     objects:           234 KiB
2016-12-16 16:17:22 fast-import:---------------------------------------------------------------------
2016-12-16 16:17:22 fast-import:pack_report: getpagesize()            =       4096
2016-12-16 16:17:22 fast-import:pack_report: core.packedGitWindowSize = 1073741824
2016-12-16 16:17:22 fast-import:pack_report: core.packedGitLimit      = 8589934592
2016-12-16 16:17:22 fast-import:pack_report: pack_used_ctr            =         61
2016-12-16 16:17:22 fast-import:pack_report: pack_mmap_calls          =         21
2016-12-16 16:17:22 fast-import:pack_report: pack_open_windows        =          1 /          1
2016-12-16 16:17:22 fast-import:pack_report: pack_mapped              =     120313 /     120313
2016-12-16 16:17:22 fast-import:---------------------------------------------------------------------
2016-12-16 16:17:22 fast-import:
Exception in thread "main" java.lang.NullPointerException
        at org.sync.GitImporter.generateFastImportStream(GitImporter.java:221)
        at org.sync.GitImporter.generateAllLabelImport(GitImporter.java:751)
        at org.sync.GitImporter.generateAllViewsImport(GitImporter.java:855)
        at org.sync.MainEntry.main(MainEntry.java:293)

Environment:
Starteam SDK 9.0
CentOS 7 
Oracle Java 1.7.0_80
Git 1.8.3.1-6

Could you please help me a little to identify whats wrong with the tool or setup ?

If I am right the issue is in "userName = userAccount.getName();" line of GitImporter.java but at the moment I don't have any idea what it is generating a null pointer exception.

**Comment by planestraveler** [comment]
I think you actually found a bug in the code regarding user account information. It does seem the UID doesn't have a user account associated.

So i don't think you have a setup issue. A proper patch would be to check that the UserAccount object isn't null and if it is, fallback to the alternative behavior (Name.SurName@domain). I'll gladly accept patch if you want to test yourself the correction.

**Comment by arpadhajdu** [comment]
Well I am not a Java programmer so I am pretty sure I won't be able to create the patch ... 
But I can test any kind of fix...

**Comment by planestraveler** [comment]
I've pushed some modifications that should make it work in your case. It would still be possible that the User object would also be null. Please advise if your issue isn't fixed.

**Comment by arpadhajdu** [comment]
I ran a test and I can confirm that the issue is now fixed. I was able to export Starteam :) 
Thank you very much!
