### ISSUE TITLE
Does it work with Starteam SDK 14?

### ISSUE THREAD

**Issue by rcowham** [planestraveler/git-starteam#69]
Managed to get it working with the starteam110.bridgeTo.starteam140.jar added to classpath, but an attempt to create a dump file, e.g.

    <usual stuff> --verbose -A -W AVP -D d:\work\export

```
:
2022-05-18 11:12:05 gc:Nothing new to pack.
Exception in thread "main" java.lang.NullPointerException
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1010)
        at org.sync.githelper.GitHelper.grabTrackedFiles(GitHelper.java:162)
        at org.sync.githelper.GitHelper.getListOfTrackedFile(GitHelper.java:378)
        at org.sync.MainEntry.main(MainEntry.java:298)
```

**Comment by rcowham** [comment]
OK, got past the above with `-H main` for current git usage.
Also needed to set `-x __dummy__`  to avoid another null exception.
Looking better...

**Comment by rcowham** [comment]
OK - so it seems to work fine having avoided the 2 issues above - maybe that's a good thing to document, and/or catch in the code...
